version: "3"
services:
  main_app:
    build: .
    ports:
      - "8081:9090"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE="employee"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
